//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoQuizAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.GameLog = new HashSet<GameLog>();
            this.Session = new HashSet<Session>();
        }
    
        public int GameID { get; set; }
        public int PlayerID { get; set; }
        public int QuestionSetID { get; set; }
        public bool IsGameEnded { get; set; }
        public long TotalTimeUsed { get; set; }
        public long ActualTimeUsed { get; set; }
        public string GameSequence { get; set; }
        public Nullable<int> TotalScore { get; set; }
        public Nullable<int> MaxConsecutiveScore { get; set; }
        public Nullable<int> MostRecentEndedQuestionID { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual QuestionSet QuestionSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameLog> GameLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Session { get; set; }
    }
}
