//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoQuizAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameLog
    {
        public int GameID { get; set; }
        public int QuestionID { get; set; }
        public int GameSequenceAt { get; set; }
        public long TotalTimeUsed { get; set; }
        public long ActualTimeUsed { get; set; }
        public Nullable<System.DateTime> At { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Question Question { get; set; }
    }
}
