//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoQuizAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int SessionID { get; set; }
        public int GameID { get; set; }
        public int QuestionID { get; set; }
        public Nullable<long> TimeLeftBeforeAsk { get; set; }
        public System.DateTime AskAt { get; set; }
        public Nullable<int> Answer { get; set; }
        public Nullable<bool> IsAnsered { get; set; }
        public Nullable<bool> isCorrect { get; set; }
        public Nullable<long> TimeLeftAfterAnswer { get; set; }
        public Nullable<System.DateTime> AnswerAt { get; set; }
        public int GameSequenceAt { get; set; }
        public long TotalTimeUsed { get; set; }
        public long ActualTimeUsed { get; set; }
        public Nullable<bool> IsSkipped { get; set; }
        public Nullable<System.DateTime> SkippedAt { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Question Question { get; set; }
    }
}
